In [5]:
import scipy as sp
import numpy as np
import os
import matplotlib.pyplot as plt
from scipy import signal
from scipy import fftpack
import math
import csv

In [18]:
csv_dir_path = "../data/Part_1"

In [19]:
csv_paths = []

for patNum in range(1,11):
    csv_paths.append(os.path.join(csv_dir_path, str(patNum)+".csv"))

In [47]:
csv_paths = []

for patNum in range(1,11):
    csv_paths.append(os.path.join(csv_dir_path, str(patNum)+".csv"))

for i in range(10):
    Y = np.genfromtxt(csv_paths[i], delimiter=",")
   
    # Calculating the number of readings in a file
    input_file = open(csv_paths[i],"r+")
    reader_file = csv.reader(input_file)
    lines = len(next(reader_file))
    #print(lines)
    ppg_Signal=[]
    BP_Signal=[]
    ECG_Signal=[]
    for i in range(0,lines,100):
        # Extracting row cooresponding to PPG signal because the first row of csv file is PPG signal
        if(i+100<lines):
            ppg_Signal = Y[0,i:i+100]
            # Extracting row cooresponding to BP signal
            BP_Signal  = Y[1,i:i+100]
            # Extracting row cooresponding to ECG signal
            ECG_Signal = Y[2,i:i+100]
            i+=100
        else:
            
            ppg_Signal = Y[0,i:]
            # Extracting row cooresponding to BP signal
            BP_Signal  = Y[1,i:]
            # Extracting row cooresponding to ECG signal
            ECG_Signal = Y[2,i:]
            i=i+100
        
        """if(len(ppg_Signal)!=100):
            print(len(ppg_Signal))
        """
        Fy  = np.gradient(ppg_Signal)

        # figure('PPG 1st derivative')
        # Uncomment below to check the graphs found from the first derivative of PPG
        """
        plt.plot(range(len(Fy)),Fy)
        plt.xlabel("PPG first derivative")
        plt.show()
        """

        Fy1 = np.gradient(Fy)

        # figure('PPG 2nd derivative')
        # Uncomment below to check the graphs found from the second derivative of PPG
        """
        plt.plot(range(len(Fy)),Fy)
        plt.xlabel("PPG second derivative")
        plt.show()
        """
        F = np.ones(100)
        np.append(F, ppg_Signal)
        np.append(F, BP_Signal)
        np.append(F, ECG_Signal)
        
        L = len(BP_Signal)

        # Sampling frequency = 125 Hz
        Fs = 125
        # Time vector based on sampling rate
        Ts = 1 / Fs

        T = np.arange(0, 8, 0.008) 
        
        #Find peaks or local maximum of PPG signals
        [peaks, location] = signal.find_peaks(ECG_Signal)
        
        print(peaks)
        
        # RR wave feature Extraction _______________________
        [RR_Wave_duration]=[]
        [s_no]=[]
        for i in range (len(peaks)-1):
            RR_Wave_duration.append(location[i+1]-location[i])
            s_no.append(i)
            
            
            

        
    

[16 27 38 52 89]
[ 1 13 40 51 62 75]
[12 19 23 38 74 85]
[27 35 42 47 61 86 96]
[ 8 19 46 57 68 82]
[17 24 29 44 68 78 89]
[ 4 27 38 50 64 88]
[10 22 58 70 85]
[18 25 30 44 69 79 90]
[ 4 28 39 51 65 89]
[ 7 11 26 49 59 66 71 87]
[20 31 46 81 92]
[ 6 31 41 48 53 66 90]
[ 2  9 14 27 51 54 62 69 74 89]
[14 23 35 49 84 96]
[ 9 45 57 68 92 97]
[ 5 17 32 66 72 77 90]
[16 27 39 53 88 94]
[15 35 49 56 61 73 76]
[10 21 36 71 78 83 97]
[22 32 39 44 58 94]
[ 5 15 43 54 66 80]
[15 21 26 42 76 87]
[ 1 36 43 48 62 97]
[ 9 21 46 57 69 81]
[18 29 43 67 78 90]
[ 3 31 39 50 64 88]
[11 21 26 48 59 70 85]
[19 30 44 69 79 90]
[ 5 28 39 46 51 64 88]
[11 22 51 59 66 71 86]
[19 31 46 70 80 91]
[ 6 31 41 47 52 66 90]
[ 2 13 22 26 50 62 69 74 89]
[23 29 34 49 73 84 96]
[11 35 46 57 71]
[ 7 19 31 35 68 79 94]
[29 40 55 81 90]
[ 2 16 41 52 63 78]
[13 19 24 37 63 73 80 85]
[24 34 46 59 87 95]
[ 7 21 56 63 68 80]
[ 7 17 28 42 77 84 89]
[ 4 38 45 50 65 88]
[11 26 49 61 73 86]
[21 27 33 48 82 89 94]
[ 8 44 56 70 96]
